### ISSUE TITLE
Proposal to rename to heka_dashboard_exporter

### ISSUE THREAD

**Issue by discordianfish** [docker-infra/heka_exporter#2]
Hi @xbglowx and @avinson,

I've wrote a new exporter which acts as a UdpInput (probably add TCP as well).
It reads a config file where you can define metrics and point it to a heka field which it will expose.
That one is actually exposing heka metrics where this one here is rather exposing dashboard metrics.

So do you think it make sense to rename this so I can name my heka_exporter?

**Comment by xbglowx** [comment]
I like the idea. Do you have your exporter available for me to test? 

I won't be able to rename and try the new exporter until next week.

**Comment by discordianfish** [comment]
@xbglowx Just released it: https://github.com/imgix/heka_exporter Let me know what you think!

**Comment by xbglowx** [comment]
Taking a look at your exporter now.

**Comment by xbglowx** [comment]
@discordianfish I am OK with the rename. I will work on this either today or tomorrow.

**Comment by xbglowx** [comment]
@discordianfish rename is done for the repo. Going through the repo and updating references as well.

**Comment by xbglowx** [comment]
All done on my end.

**Comment by discordianfish** [comment]
Awesome, thanks!
